repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace      # убирает лишние пробелы
        files: \.(py|sh|rst|yml|yaml)$
      - id: check-added-large-files  # проверяет тяжелые файлы на изменения
      - id: check-yaml               # проверяет синтаксис .yaml файлов
      - id: check-json               # проверяет синтаксис .json файлов
      - id: check-case-conflict   # проверяет файлы, которые могут конфликтовать в файловых системах без учета регистра.
      - id: check-merge-conflict  # проверяет файлы, содержащие конфликтные строки слияния.
#      - id: double-quote-string-fixer  # заменяет " на '
      - id: end-of-file-fixer          # добавляет пустую строку в конце файла
      - id: debug-statements

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        exclude: __init__.py
        args: [ --profile, black, --line-length=79, ]

  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: [--line-length=90, --target-version=py310]

  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        entry: autoflake
        language: system
        types: [python]
        exclude: __init__.py
        args: [
          --in-place,
          --ignore-init-module-imports,
          --remove-all-unused-imports,
          --remove-duplicate-keys,
          --ignore-pass-statements,
        ]

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        args: [
           "--ignore=ANN101,ANN102,ANN401,
           E203,
           FI10,FI11,FI12,FI13,FI14,FI15,FI16,FI17,FI18,FI58,
           PT013,
           S101,
           S404,
           T000,T101,
           W503",
           "--extend-immutable-calls=fastapi.Depends,fastapi.params.Depends,Depends",
           #
               # ANN101 Missing type annotation for self in method
               # ANN102 Missing type annotation for cls in classmethod
               # ANN401 Dynamically typed expressions (typing.Any) are disallowed
           # black
               # E203 whitespace before ':'
               # W503 line break before binary operator
           # flake8-future-import
               # FI10 __future__ import "division" missing
               # FI11 __future__ import "absolute_import" missing
               # FI12 __future__ import "with_statement" missing
               # FI13 __future__ import "print_function" missing
               # FI14 __future__ import "unicode_literals" missing
               # FI15 __future__ import "generator_stop" missing
               # FI16 __future__ import "nested_scopes" missing
               # FI17 __future__ import "generators" missing
               # FI18 __future__ import "annotations" missing
               # FI58 __future__ import "annotations" present
           # flake8-pytest-style
               # PT013 found incorrect import of pytest, use simple 'import pytest' instead
           "--max-line-length=110",
           "--per-file-ignores=tests/*.py:S101"
           # S101 Use of assert detected
        ]


  - repo: local
    hooks:
      - id: pyupgrade
        name: pyupgrade
        entry: pyupgrade
        language: system
        types: [python]
        args: [--py38]

  - repo: local
    hooks:
      - id: yesqa
        name: yesqa
        entry: yesqa
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [python]
        exclude:  |
          (?x)^(
              migrations/.*|
              alembic/.*|
              tests/.*
          )$
        args: [ --show-error-codes ]
        additional_dependencies: [
          types-requests,
        ]

#  - repo: local
#    hooks:
#      - id: pytest-check
#        name: pytest-check
#        entry: pytest
#        language: system
#        pass_filenames: false
#        always_run: true

exclude: |
    (?x)(
        ^alembic/|
        ^samples/|
        ^docs/|
        ^.venv/|
        ^.idea/
    )
